sudo: false
language: ruby
rvm:
  - "2.2.0"
git:
  depth: 10
branches:
  only:
    - "source"
before_install:
  - "npm install -g npm@\"^3.0.0\""
install:
  - "bundle install"
  - "npm install"
script:
  - "jekyll build"
after_success:
  - |
      $(npm bin)/update-branch --commands "true" \
                               --commit-message "Update site [ci skip]" \
                               --directory "_site" \
                               --distribution-branch "master" \
                               --source-branch "source"
