name: d10.github.io
description: "Benjamin Tan (@d10) posts random stuff here."
url: https://d10.github.io
id: "tag:d10.github.io,2014:/blog"
exclude:
  - "LICENSE"
  - "README.md"
permalink: /blog/:title/
