name: "@demoneaux"
description: "Benjamin Tan posts random stuff here."
url: "https://demoneaux.github.io"
author: "Benjamin Tan"
exclude:
  - "LICENSE"
  - "README.md"
permalink: "/blog/:title/"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      html_id: "post"
gems:
  - "jekyll-last-modified-at"
  - "jekyll-sitemap"
